#!/usr/bin/env nextflow

// Copyright (C) 2017 IARC/WHO

// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.

// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.

// You should have received a copy of the GNU General Public License
// along with this program.  If not, see <http://www.gnu.org/licenses/>.

// Usage: nextflow run CirRealign.nf --cpu 2 --output_folder ./test5 -resume

params.input_summary = './pass_samples.txt'
params.output_folder = "."
params.ref_sublineage_folder = "/data/HPVCar/work/Sangphukieo/HPV_SEQ_ALIGN_PIPELINE/00_INPUT/ref_sublinage/"
params.elongation = 400
params.cpu = 2
params.mem = 40


log.info ""
log.info "---------------------------------------------------------------------------------------------------------"
log.info "           CirRealign pipeline for HPV16 realignment to each specific sub-lineage reference              "
log.info "---------------------------------------------------------------------------------------------------------"
log.info "Copyright (C) IARC/WHO"
log.info "This program comes with ABSOLUTELY NO WARRANTY; for details see LICENSE"
log.info "This is free software, and you are welcome to redistribute it"
log.info "under certain conditions; see LICENSE for details."
log.info "--------------------------------------------------------"
log.info "=========== Pre-installed required =============="
log.info "abra2, bwa-aln, circularMapper"
log.info "--------------------------------------------------------"
if (params.help) {
    log.info "--------------------------------------------------------"
    log.info "                     USAGE                              "
    log.info "--------------------------------------------------------"
    log.info " version 1.2: replace Bwa-aln with Bwa-mem for gap-containing read pipeline as it yield more mapped reads, and keep using Bwa-aln for no-gap read pipeline as it yields more no-gap reads"
    log.info " version 1.1: updated alignment with sublineage genome without elongation factor, and merge all aligned reads (without and with elongation factor)"
    log.info "--------------------------------------------------"
    log.info ""
    log.info "nextflow run CirRealign.nf --input_summary pass_samples.txt --output_folder ./01_CirRealign"
    log.info ""
    log.info "Mandatory arguments:"
    log.info "--input_summary        FILE                 File containg list of selected files that pass HPV16(+) criteria with predicted HPV16 sublineage (generated by QC pipeline and filter_sample.R script)"
    log.info ""
    log.info "Optional arguments:"
    log.info "--ref_sublineage_folder         PATH        Folder containig HPV16 reference genomes with elonged region"
    log.info "--output_folder        PATH                 Output directory for html and zip files (default=.)"
    log.info "--elongation           STRING                  Elongation factor used for HPV16 reference genomes (default=400)"
    log.info "--cpu                  INTEGER              Number of cpu to use (default=1)"
    log.info "--mem                  INTEGER              Size of memory used. Default 4Gb"
    log.info ""
    log.info "Flags:"
    log.info "--help                                      Display this message"
    log.info ""
    exit 0
}else{
/* Software information */
  log.info "cpu            = ${params.cpu}"
  log.info "mem            = ${params.mem}"
  log.info "input_summary   = ${params.input_summary}"
  log.info "output_folder  = ${params.output_folder}"
  log.info "ref_sublineage_folder  = ${params.ref_sublineage_folder}"
  log.info "elongation = ${params.elongation}"
  log.info "help           = ${params.help}"
}

assert (params.input_summary != null) : "please provide the --input_summary option"

//input: summary_table.txt, output, path_to_bam_input
//Rscript /data/HPVCar/work/Sangphukieo/HPV_SEQ_ALIGN_PIPELINE/NF_test/filter_sample.R /data/HPVCar/work/Sangphukieo/HPV_SEQ_ALIGN_PIPELINE/NF_test/path_output10/summary_table.txt filtered_samples.txt /data/HPVCar/work/Sangphukieo/HPV_SEQ_ALIGN_PIPELINE/NF_test/path_output10
filtered_list = Channel.fromPath(params.input_summary)
    .splitCsv()

filtered_list.into{ filtered_bam}

//Start first alignment by BWA aln
process bwa_aln {
    //errorStrategy 'ignore'
    cpus params.cpu
    memory params.mem+'G'
    queue 'low_p'
    tag { bam_tag }

    publishDir "${params.output_folder}/bwa_bam", mode: 'copy'

    input:
    tuple sample, lineage , path(bam) from filtered_bam

    output:
    tuple lineage, file("${bam_tag}.cirmapper_nogap.bam") into bwa_out
    file("${bam_tag}.cirmapper_nogap.flag") into bwa_flag
    file("${bam_tag}.cirmapper.flag") into bwa_gap_flag
    tuple sample, lineage , file("${bam_tag}.cirmapper_gap.bam") into gap_bam

    shell:
    bam_tag=bam.toString().tokenize('.').get(0)

    """    
    tagID=\$(samtools view -H ${bam} |grep ^@RG| cut -f2|  awk -F":" '{print \$NF}')
    tagSM=\$(samtools view -H ${bam} |grep ^@RG| cut -f3|  awk -F":" '{print \$NF}')

    samtools sort -n ${bam} -o !{bam_tag}_sort.bam
    
    samtools fastq -T "RG" -@ ${params.cpu} !{bam_tag}_sort.bam \
        -1 !{bam_tag}_1.fastq \
        -2 !{bam_tag}_2.fastq \
        -0 /dev/null -s /dev/null -n

    bwa aln -t ${params.cpu} ${params.ref_sublineage_folder}${lineage}_${params.elongation}.fasta -1 !{bam_tag}_1.fastq -n 0.04 -l 32  -f !{bam_tag}_1.sai
    bwa aln -t ${params.cpu} ${params.ref_sublineage_folder}${lineage}_${params.elongation}.fasta -2 !{bam_tag}_2.fastq -n 0.04 -l 32  -f !{bam_tag}_2.sai

    bwa sampe -r "@RG\\tID:\${tagID}\\tSM:\${tagSM}" ${params.ref_sublineage_folder}${lineage}_${params.elongation}.fasta !{bam_tag}_1.sai !{bam_tag}_2.sai !{bam_tag}_1.fastq !{bam_tag}_2.fastq -f !{bam_tag}_cirmapper.sam

    samtools flagstat !{bam_tag}_cirmapper.sam > !{bam_tag}.cirmapper.flag.tmp
    paste <(echo !{bam_tag} ) <(cut -f1 -d" " !{bam_tag}.cirmapper.flag.tmp |awk '{printf \$0"\t"}'| sed s/"\t\$"//g) <(grep "Number" !{bam_tag}.cirmapper.flag.tmp | cut -f2 -d ":" |sed s/" "/""/g| awk '{printf \$0"\t"}') > !{bam_tag}.cirmapper.flag

    read_len=\$(samtools stats !{bam_tag}_cirmapper.sam | grep "maximum length" | cut -f 3)

    samtools view -h !{bam_tag}_cirmapper.sam| awk -v read_len=\${read_len} ' \$6 == read_len"M" || \$1 ~ /^@/ ' | samtools view -bS - > !{bam_tag}.cirmapper_nogap.bam
    samtools view -h !{bam_tag}_cirmapper.sam| awk -v read_len=\${read_len} ' \$6 != read_len"M" || \$1 ~ /^@/ ' | samtools view -bS - > !{bam_tag}.cirmapper_gap.bam

    samtools flagstat !{bam_tag}.cirmapper_nogap.bam > !{bam_tag}.cirmapper_nogap.flag.tmp
    paste <(echo !{bam_tag} ) <(cut -f1 -d" " !{bam_tag}.cirmapper_nogap.flag.tmp |awk '{printf \$0"\t"}'| sed s/"\t\$"//g) <(grep "Number" !{bam_tag}.cirmapper_nogap.flag.tmp | cut -f2 -d ":" |sed s/" "/""/g| awk '{printf \$0"\t"}') > !{bam_tag}.cirmapper_nogap.flag
    """
}

//to align reads that contain gap (not compatible with CircularMapper-realign) to un-elongated genome
process bwa_mem_wo_elongation {
    //errorStrategy 'ignore'
    cpus params.cpu
    memory params.mem+'G'
    queue 'low_p'
    tag { bam_tag }

    publishDir "${params.output_folder}/bwa_bam_wo_elongation", mode: 'copy'

    input:
    tuple sample, lineage , file(bam) from gap_bam

    output:
    tuple lineage, file("${bam_tag}.gap.bam") into bwa_gap_out
    file("${bam_tag}.gap.flag") into bwa_gap_wo_elongation_flag

    shell:
    bam_tag=bam.toString().tokenize('.').get(0)

    """    
    tagID=\$(samtools view -H ${bam} |grep ^@RG| cut -f2|  awk -F":" '{print \$NF}')
    tagSM=\$(samtools view -H ${bam} |grep ^@RG| cut -f3|  awk -F":" '{print \$NF}')

    samtools sort -n ${bam} -o !{bam_tag}_sort.bam
    
    samtools fastq -T "RG" -@ ${params.cpu} !{bam_tag}_sort.bam \
        -1 !{bam_tag}_1.fastq \
        -2 !{bam_tag}_2.fastq \
        -0 /dev/null -s /dev/null -n

    bwa mem -Y -M -R "@RG\\tID:\${tagID}\\tSM:\${tagSM}" -t ${params.cpu} ${params.ref_sublineage_folder}${lineage}.fasta !{bam_tag}_1.fastq !{bam_tag}_2.fastq > !{bam_tag}_gap.sam
    samtools view -bS !{bam_tag}_gap.sam > !{bam_tag}.gap.bam

    samtools flagstat !{bam_tag}.gap.bam > !{bam_tag}.gap.flag.tmp
    paste <(echo !{bam_tag} ) <(cut -f1 -d" " !{bam_tag}.gap.flag.tmp |awk '{printf \$0"\t"}'| sed s/"\t\$"//g) <(grep "Number" !{bam_tag}.gap.flag.tmp | cut -f2 -d ":" |sed s/" "/""/g| awk '{printf \$0"\t"}') > !{bam_tag}.gap.flag
    """
}


process abra_wo_elongation {
    //errorStrategy 'ignore'
    cpus params.cpu
    memory params.mem
    queue 'low_p'
    tag { bam_tag }

    publishDir "${params.output_folder}/abra_bam_wo_elongation", mode: 'copy'

    input:
    tuple lineage, file(bam_bwa) from bwa_gap_out

    output:
    tuple bam_tag, file("${bam_tag}.gap_sort_abra.bam") into arba_gap_bam

    shell:
    bam_tag=bam_bwa.toString().tokenize('.').get(0)

    """
    samtools sort ${bam_bwa} > !{bam_tag}_gap_sort.bam
    samtools index !{bam_tag}_gap_sort.bam

    abra2 \
        --in !{bam_tag}_gap_sort.bam \
        --out  !{bam_tag}.gap_sort_abra.bam \
        --ref "${params.ref_sublineage_folder}${lineage}.fasta" \
        --threads ${params.cpu} \
        --targets "${params.ref_sublineage_folder}${lineage}.fasta.bed"
    """

}

process abra {
    errorStrategy 'ignore'
    cpus params.cpu
    memory params.mem
    queue 'low_p'
    tag { bam_tag }

    publishDir "${params.output_folder}/abra_bam", mode: 'copy'

    input:
    tuple lineage, file(bam_bwa) from bwa_out

    output:
    tuple lineage, file("${bam_tag}.cirmapper_nogap_sort_abra.bam") into arba_bam

    shell:
    bam_tag=bam_bwa.toString().tokenize('.').get(0)

    """
    samtools sort ${bam_bwa} > !{bam_tag}_cirmapper_nogap_sort.bam
    samtools index !{bam_tag}_cirmapper_nogap_sort.bam

    abra2 \
        --in !{bam_tag}_cirmapper_nogap_sort.bam \
        --out  !{bam_tag}.cirmapper_nogap_sort_abra.bam \
        --ref "${params.ref_sublineage_folder}${lineage}_${params.elongation}.fasta" \
        --threads ${params.cpu} \
        --targets "${params.ref_sublineage_folder}${lineage}_${params.elongation}.fasta.bed"
    """

}

process realignsamfile {
    //errorStrategy 'ignore'
    cpus params.cpu
    memory params.mem
    queue 'low_p'
    tag { bam_tag }

    publishDir "${params.output_folder}/realigned_bam", mode: 'copy'

    input:
    tuple lineage, file(bam_abra) from arba_bam

    output:
    file("${bam_tag}_realign.flag") into realign_flag
    tuple bam_tag, file("${bam_tag}.cirmapper_nogap_sort_abra_realigned.bam") into realign_bam
    file("${bam_tag}.cirmapper_nogap_sort_abra_realigned.bam.bai")

    shell:
    bam_tag=bam_abra.toString().tokenize('.').get(0)

    """
    realignsamfile -e ${params.elongation} -i !{bam_abra} -r "${params.ref_sublineage_folder}${lineage}_${params.elongation}.fasta" > !{bam_tag}_realign_out.tmp
    samtools flagstat !{bam_tag}.cirmapper_nogap_sort_abra_realigned.bam > !{bam_tag}_realigned.tmp
    samtools index !{bam_tag}.cirmapper_nogap_sort_abra_realigned.bam

    paste <(echo !{bam_tag} ) <(cut -f1 -d" " !{bam_tag}_realigned.tmp|awk '{printf \$0"\t"}'| sed s/"\t\$"//g) <(grep "Number" !{bam_tag}_realign_out.tmp | cut -f2 -d ":" |sed s/" "/""/g| awk '{printf \$0"\t"}') > !{bam_tag}_realign.flag
    """

}

//to merge reads from reads with gap channel and reads without gap channel
process merge_aligned_reads {
    //errorStrategy 'ignore'
    cpus params.cpu
    memory params.mem
    queue 'low_p'
    tag { pair }

    publishDir "${params.output_folder}/final_realigned_bam", mode: 'copy'

    input:
    tuple val(pair), file(no_gap_bam), file(gap_bam) from realign_bam.join(arba_gap_bam)

    output:
    file("${pair}.merged.bam") into merge_bam
    file("${pair}.merged.bam.bai")
    file("${pair}_merge.flag") into merge_bam_flag

    shell:
    """
    samtools merge -f -cp !{pair}.merged.bam !{gap_bam} !{no_gap_bam}
    samtools flagstat !{pair}.merged.bam > !{pair}_merge.tmp
    samtools index !{pair}.merged.bam

    paste <(echo !{pair} ) <(cut -f1 -d" " !{pair}_merge.tmp |awk '{printf \$0"\t"}'| sed s/"\t\$"//g) <(grep "Number" !{pair}_merge.tmp | cut -f2 -d ":" |sed s/" "/""/g| awk '{printf \$0"\t"}') > !{pair}_merge.flag
    """

}

process summaryAlignment_Cir {
    //errorStrategy 'ignore'
    cpus params.cpu
    memory params.mem
    queue 'low_p'

    publishDir "${params.output_folder}", mode: 'copy'

    input:
    file realign_flag from realign_flag.collect()

    output:
    file("summary_realign_Cir.out")

    script:

    """
    cat <(echo -e "Sample\tin total (QC-passed reads + QC-failed reads)\tsecondary\tsupplementary\tduplicates\tmapped\tpaired in sequencing\tread1\tread2\tproperly paired\twith itself and mate mapped\tsingletons\twith mate mapped to a different chr\twith mate mapped to a different chr (mapQ>=5)\tNumber of overlapping reads\tNumber of reads in regular genome\tNumber of reads in elongation factor completely\tNumber of reads in first n bases, where n is the length of the elongation") <(cat ${realign_flag} ) > summary_realign_Cir.out
    """

}

process summaryAlignment_Bwa {
    //errorStrategy 'ignore'
    cpus params.cpu
    memory params.mem
    queue 'low_p'

    publishDir "${params.output_folder}", mode: 'copy'

    input:
    file bwa_flag from bwa_flag.collect()

    output:
    file("summary_realign_Bwa.out")

    script:

    """
    cat <(echo -e "Sample\tin total (QC-passed reads + QC-failed reads)\tsecondary\tsupplementary\tduplicates\tmapped\tpaired in sequencing\tread1\tread2\tproperly paired\twith itself and mate mapped\tsingletons\twith mate mapped to a different chr\twith mate mapped to a different chr (mapQ>=5)\tNumber of overlapping reads\tNumber of reads in regular genome\tNumber of reads in elongation factor completely\tNumber of reads in first n bases, where n is the length of the elongation") <(cat ${bwa_flag} ) > summary_realign_Bwa.out
    """

}

process summaryAlignment_Bwa_gap {
    //errorStrategy 'ignore'
    cpus params.cpu
    memory params.mem
    queue 'low_p'

    publishDir "${params.output_folder}", mode: 'copy'

    input:
    file bwa_gap_flag from bwa_gap_flag.collect()

    output:
    file("summary_realign_Bwa_gap.out")

    script:

    """
    cat <(echo -e "Sample\tin total (QC-passed reads + QC-failed reads)\tsecondary\tsupplementary\tduplicates\tmapped\tpaired in sequencing\tread1\tread2\tproperly paired\twith itself and mate mapped\tsingletons\twith mate mapped to a different chr\twith mate mapped to a different chr (mapQ>=5)\tNumber of overlapping reads\tNumber of reads in regular genome\tNumber of reads in elongation factor completely\tNumber of reads in first n bases, where n is the length of the elongation") <(cat ${bwa_gap_flag} ) > summary_realign_Bwa_gap.out
    """

}

process summaryAlignment_merge {
    //errorStrategy 'ignore'
    cpus params.cpu
    memory params.mem
    queue 'low_p'

    publishDir "${params.output_folder}", mode: 'copy'

    input:
    file merge_bam_flag from merge_bam_flag.collect()

    output:
    file("summary_realign_all.out")

    script:

    """
    cat <(echo -e "Sample\tin total (QC-passed reads + QC-failed reads)\tsecondary\tsupplementary\tduplicates\tmapped\tpaired in sequencing\tread1\tread2\tproperly paired\twith itself and mate mapped\tsingletons\twith mate mapped to a different chr\twith mate mapped to a different chr (mapQ>=5)\tNumber of overlapping reads\tNumber of reads in regular genome\tNumber of reads in elongation factor completely\tNumber of reads in first n bases, where n is the length of the elongation") <(cat ${merge_bam_flag} ) > summary_realign_all.out
    """

}